#!/bin/sh

# do all small problems (OK on a laptop with 16GB RAM)

./mklgrb_transpose ../MM/ND/nd3k/nd3k.lagraph
./mklgrb_transpose ../MM/ND/nd24k/nd24k.lagraph
./mklgrb_transpose ../MM/SNAP/roadNet-CA/roadNet-CA.lagraph
./mklgrb_transpose ../MM/SNAP/soc-Pokec/soc-Pokec.lagraph
./mklgrb_transpose ../MM/Freescale/Freescale2/Freescale2.lagraph
./mklgrb_transpose ../MM/LAW/indochina-2004/indochina-2004.lagraph
./mklgrb_transpose ../MM/SNAP/com-Orkut/com-Orkut.lagraph
